# Generated by Django 3.2.9 on 2022-02-16 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=254, unique=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('poll_id', models.AutoField(primary_key=True, serialize=False)),
                ('poll_name', models.CharField(max_length=150)),
                ('poll_status', models.CharField(choices=[('0', 'Inactive'), ('1', 'Ongoing'), ('2', 'Closed')], max_length=2)),
                ('public_key', models.CharField(max_length=256)),
                ('private_key_l', models.CharField(max_length=256)),
                ('private_key_m', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'poll',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PollOptions',
            fields=[
                ('option_id', models.AutoField(primary_key=True, serialize=False)),
                ('option_num', models.IntegerField(null=True)),
                ('option_name', models.CharField(max_length=150)),
                ('poll_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.poll')),
            ],
            options={
                'db_table': 'poll_options',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_choice', models.IntegerField(default=0)),
                ('option_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.polloptions')),
                ('poll_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.poll')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_vote',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.poll')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_poll',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserBallot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_choice', models.IntegerField(default=0)),
                ('option_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.polloptions')),
                ('poll_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.poll')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_ballot',
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='userpoll',
            constraint=models.UniqueConstraint(fields=('poll_id', 'user_id'), name='userpoll_poll_user_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='userballot',
            constraint=models.UniqueConstraint(fields=('poll_id', 'user_id', 'option_num'), name='userballot_poll_user_id_option_unique'),
        ),
        migrations.AddConstraint(
            model_name='polloptions',
            constraint=models.UniqueConstraint(fields=('option_id', 'option_name', 'option_num'), name='option_id_name_num_unique'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('username', 'email')},
        ),
    ]
