# Generated by Django 3.2.9 on 2022-02-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userballot',
            name='user_choice',
            field=models.CharField(max_length=256),
        ),
    ]
